---

- name: Wireguard | Checking config
  ansible.builtin.assert:
    that:
      - wireguard is defined
      - wireguard.topologies is defined
  tags: [purge, tunnels, config]

- name: Wireguard | Skipping host => not configured in any wireguard-topology
  ansible.builtin.meta: end_host
  when: "inventory_hostname not in wireguard.topologies | flatten_hosts"
  tags: [purge, tunnels, config]

- name: Wireguard | Processing debian config
  ansible.builtin.import_tasks: debian/main.yml
  when: "ansible_distribution|lower in ['debian', 'ubuntu']"
